/**
 * Private document storage (SEC-010, SEC-011).
 *
 * The only implementation is a local directory for development and tests.
 * Production storage (object storage, encryption at rest, backup, retention)
 * has not been chosen; see ADR 0006. Anything new must keep the same contract:
 * keys are generated by the server, never derived from a filename, and files
 * are reachable only through the authorized download endpoint — there is no
 * public URL of any kind.
 */
import { createHash, randomUUID } from 'node:crypto';
import { createReadStream, createWriteStream } from 'node:fs';
import { mkdir, readdir, readFile, rename, rm, stat } from 'node:fs/promises';
import path from 'node:path';
import { Transform, type Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';

const KEY_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

export class UploadTooLargeError extends Error {
  constructor() {
    super('Upload exceeds the configured size limit.');
    this.name = 'UploadTooLargeError';
  }
}

export interface StoredObject {
  key: string;
  byteSize: number;
  sha256: string;
}

export interface DocumentStorage {
  /** Streams into a new object under a generated key; enforces the size limit while writing. */
  put(source: Readable, maxBytes: number): Promise<StoredObject>;
  read(key: string): Promise<Buffer>;
  open(key: string): Readable;
  /** Moves an object out of the serving area after a positive scan. */
  quarantine(key: string): Promise<void>;
  remove(key: string): Promise<void>;
  /** Keys of stored objects last written before `olderThan`. */
  listOlderThan(olderThan: Date): Promise<string[]>;
}

export class LocalDocumentStorage implements DocumentStorage {
  private readonly objects: string;
  private readonly quarantined: string;

  constructor(root: string) {
    const resolved = path.resolve(root);
    this.objects = path.join(resolved, 'objects');
    this.quarantined = path.join(resolved, 'quarantine');
  }

  /** Keys are server-generated UUIDs; anything else never reaches the filesystem. */
  private pathFor(key: string, area: string = this.objects): string {
    if (!KEY_PATTERN.test(key)) throw new Error('Invalid storage key.');
    return path.join(area, key.slice(0, 2), key);
  }

  async put(source: Readable, maxBytes: number): Promise<StoredObject> {
    const key = randomUUID();
    const target = this.pathFor(key);
    await mkdir(path.dirname(target), { recursive: true, mode: 0o700 });

    const hash = createHash('sha256');
    let byteSize = 0;
    const meter = new Transform({
      transform(chunk: Buffer, _encoding, callback) {
        byteSize += chunk.length;
        if (byteSize > maxBytes) {
          callback(new UploadTooLargeError());
          return;
        }
        hash.update(chunk);
        callback(null, chunk);
      },
    });

    try {
      await pipeline(source, meter, createWriteStream(target, { flags: 'wx', mode: 0o600 }));
    } catch (error) {
      await rm(target, { force: true });
      throw error;
    }
    return { key, byteSize, sha256: hash.digest('hex') };
  }

  read(key: string): Promise<Buffer> {
    return readFile(this.pathFor(key));
  }

  open(key: string): Readable {
    return createReadStream(this.pathFor(key));
  }

  async quarantine(key: string): Promise<void> {
    const target = this.pathFor(key, this.quarantined);
    await mkdir(path.dirname(target), { recursive: true, mode: 0o700 });
    await rename(this.pathFor(key), target);
  }

  async remove(key: string): Promise<void> {
    await rm(this.pathFor(key), { force: true });
  }

  async listOlderThan(olderThan: Date): Promise<string[]> {
    const keys: string[] = [];
    let shards: string[];
    try {
      shards = await readdir(this.objects);
    } catch {
      return keys;
    }
    for (const shard of shards) {
      const entries = await readdir(path.join(this.objects, shard)).catch(() => [] as string[]);
      for (const entry of entries) {
        if (!KEY_PATTERN.test(entry)) continue;
        const info = await stat(path.join(this.objects, shard, entry)).catch(() => null);
        if (info && info.mtime < olderThan) keys.push(entry);
      }
    }
    return keys;
  }
}
