/**
 * CSV encoding for exports (FR-083).
 *
 * UTF-8 with a byte-order mark so spreadsheet programs read Bangla correctly,
 * CRLF line endings, a heading row, money as unformatted decimal strings, and
 * instants as ISO 8601 with the Bangladesh offset, labelled in the heading.
 *
 * Formula injection: a spreadsheet treats a cell starting with = + - @ (or a
 * tab or carriage return, which some programs skip before evaluating) as a
 * formula. Every text cell — the user-entered ones — that starts with one of
 * these, possibly after leading spaces, or with their full-width forms, is
 * prefixed with an apostrophe so it is read as text. Counts, money and dates
 * are generated by the server and are emitted as they are.
 */
import type { ReportCell } from '../../shared/api.js';
import type { ReportColumnKind } from '../../shared/reporting.js';

const FORMULA_TRIGGER = /^[\s\u00a0]*[=+\-@\uff1d\uff0b\uff0d\uff20]|^[\t\r\n]/;

export function neutralizeFormula(value: string): string {
  return FORMULA_TRIGGER.test(value) ? `'${value}` : value;
}

function quote(value: string): string {
  return /[",\r\n]|^\s|\s$/.test(value) ? `"${value.replace(/"/g, '""')}"` : value;
}

/** An instant as ISO 8601 in Bangladesh time (UTC+6, no daylight saving). */
export function toDhakaIso(iso: string): string {
  const shifted = new Date(new Date(iso).getTime() + 6 * 3_600_000);
  return `${shifted.toISOString().slice(0, 19)}+06:00`;
}

export interface CsvColumn {
  key: string;
  label: string;
  kind: ReportColumnKind;
}

function encodeCell(value: ReportCell | undefined, kind: ReportColumnKind): string {
  if (value === null || value === undefined) return '';
  switch (kind) {
    case 'instant':
      return toDhakaIso(String(value));
    case 'count':
    case 'money':
    case 'date':
    case 'percent':
      return String(value);
    default:
      return neutralizeFormula(String(value));
  }
}

function heading(column: CsvColumn): string {
  const label = column.kind === 'instant' ? `${column.label} (Bangladesh time, UTC+6)` : column.label;
  return neutralizeFormula(label);
}

export function buildCsv(columns: CsvColumn[], rows: Record<string, ReportCell>[]): string {
  const lines = [columns.map((column) => quote(heading(column))).join(',')];
  for (const row of rows) {
    lines.push(columns.map((column) => quote(encodeCell(row[column.key], column.kind))).join(','));
  }
  return `\uFEFF${lines.join('\r\n')}\r\n`;
}
