/**
 * In-app notifications (FR-090, BR-070).
 *
 * Alerts are generated by background jobs (./jobs) for follow-ups due today,
 * overdue follow-ups and tender deadlines within 72 hours, and after an
 * ownership transfer. Recipients come from `alertRecipientSql` in the policy
 * module: the responsible person, the section's lead and management, each
 * only while they can see the record.
 *
 * Three rules hold throughout:
 *
 *  - One alert per trigger. `trigger_key` = type, recipient, record and the
 *    date or deadline concerned; a repeated job inserts nothing new.
 *  - An alert is shown only while it is still true and still permitted. Every
 *    read re-checks the recipient's access and the alert's facts (the task
 *    still open with the same due date, the notice still current with the
 *    same deadline, the owner unchanged). Retirement is also written
 *    (`resolved_at`) by the services that make an alert obsolete and by the
 *    scan, but the read-time check means no stale alert is ever served.
 *  - Reading an alert records `read_at` and nothing else. It never completes,
 *    reschedules or otherwise touches the task (BR-070).
 */
import { and, asc, desc, eq, isNull, sql, type SQL } from 'drizzle-orm';
import { alias } from 'drizzle-orm/pg-core';

import type { NotificationDto, NotificationListDto } from '../../shared/api.js';
import type { NotificationType } from '../../shared/reporting.js';
import { BUSINESS_TIME_LABEL, BUSINESS_TIME_ZONE, TENDER_DUE_SOON_HOURS } from '../../shared/enums.js';
import { dhakaDateOf, now } from '../clock.js';
import type { Database } from '../db/client.js';
import { followUps, notifications, opportunities, tenders, users } from '../db/schema.js';
import { notFound } from '../http/errors.js';
import type { Actor } from '../policy/actor.js';
import { alertRecipientSql, opportunityScope } from '../policy/scope.js';
import { enqueueJob } from '../jobs/queue.js';
import { opportunityOpen, participatingCurrentNotice, tenderDueWithin } from './metrics.js';

const recipient = alias(users, 'recipient');
const assignee = alias(users, 'alert_assignee');
const subject = alias(users, 'alert_subject');

// ---------------------------------------------------------------------------
// Validity: the single definition of "this alert is still true"
// ---------------------------------------------------------------------------

/**
 * True while the alert in `notifications` still describes the current state
 * and its recipient (`recipient`) may still see the record. Expects
 * `opportunities`, `recipient`, and left-joined `follow_ups` and `tenders`
 * in the same query.
 */
function stillValid(at: Date): SQL {
  const today = dhakaDateOf(at);
  return sql`(${notifications.resolvedAt} IS NULL AND CASE ${notifications.type}
    WHEN 'follow_up_due_today' THEN
      ${followUps.state} = 'open' AND ${followUps.dueDate} = ${notifications.triggerDate}
      AND ${followUps.dueDate} = ${today}::date AND ${opportunityOpen()}
      AND ${alertRecipientSql(recipient, followUps.assignedUserId)}
    WHEN 'follow_up_overdue' THEN
      ${followUps.state} = 'open' AND ${followUps.dueDate} = ${notifications.triggerDate}
      AND ${followUps.dueDate} < ${today}::date AND ${opportunityOpen()}
      AND ${alertRecipientSql(recipient, followUps.assignedUserId)}
    WHEN 'tender_deadline' THEN
      ${participatingCurrentNotice()} AND ${tenders.submissionDeadline} = ${notifications.triggerAt}
      AND ${tenders.submissionDeadline} > ${at.toISOString()}::timestamptz
      AND ${alertRecipientSql(recipient, opportunities.ownerId)}
    WHEN 'ownership_changed' THEN
      ${opportunities.ownerId} = ${notifications.subjectUserId}
      AND ${alertRecipientSql(recipient, notifications.subjectUserId)}
    ELSE false END)`;
}

/**
 * Retires alerts that are no longer true or no longer permitted. Called inside
 * the transactions that make alerts obsolete (completion, rescheduling,
 * transfer, tender changes) and by every scan. Touches only notification rows,
 * after the caller's opportunity lock, so it never inverts the lock order.
 */
export async function retireObsoleteAlerts(
  tx: Database,
  options: { resolution: string; opportunityId?: string; followUpId?: string; tenderId?: string; at?: Date },
): Promise<number> {
  const at = options.at ?? now();
  const narrow: SQL[] = [];
  if (options.opportunityId) narrow.push(sql`${notifications.opportunityId} = ${options.opportunityId}`);
  if (options.followUpId) narrow.push(sql`${notifications.followUpId} = ${options.followUpId}`);
  if (options.tenderId) narrow.push(sql`${notifications.tenderId} = ${options.tenderId}`);

  const result = await tx.execute(sql`
    UPDATE ${notifications}
    SET resolved_at = ${at.toISOString()}::timestamptz, resolution = ${options.resolution}
    WHERE ${notifications.resolvedAt} IS NULL
      ${narrow.length > 0 ? sql`AND ${sql.join(narrow, sql` AND `)}` : sql``}
      AND NOT EXISTS (
        SELECT 1 FROM ${opportunities}
        JOIN ${users} AS ${sql.identifier('recipient')} ON ${recipient.id} = ${notifications.recipientId}
        LEFT JOIN ${followUps} ON ${followUps.id} = ${notifications.followUpId}
        LEFT JOIN ${tenders} ON ${tenders.id} = ${notifications.tenderId}
        WHERE ${opportunities.id} = ${notifications.opportunityId}
          AND ${stillValid(at)}
      )
  `);
  return result.rowCount ?? 0;
}

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

interface AlertCandidate {
  recipientId: string;
  opportunityId: string;
  followUpId: string | null;
  tenderId: string | null;
  type: NotificationType;
  triggerKey: string;
  triggerDate: string | null;
  triggerAt: Date | null;
  subjectUserId: string | null;
}

async function insertAlerts(db: Database, candidates: AlertCandidate[], at: Date): Promise<number> {
  if (candidates.length === 0) return 0;
  // Inserted in trigger-key order so two concurrent generators take the
  // unique-index entries in the same order and cannot deadlock each other.
  const sorted = [...candidates].sort((a, b) => a.triggerKey.localeCompare(b.triggerKey));
  let inserted = 0;
  for (let index = 0; index < sorted.length; index += 500) {
    const rows = await db
      .insert(notifications)
      .values(sorted.slice(index, index + 500).map((candidate) => ({ ...candidate, createdAt: at })))
      .onConflictDoNothing({ target: notifications.triggerKey })
      .returning({ id: notifications.id });
    inserted += rows.length;
  }
  return inserted;
}

const notYetAlerted = (key: SQL) =>
  sql`NOT EXISTS (SELECT 1 FROM ${notifications} WHERE ${notifications.triggerKey} = ${key})`;

/**
 * Follow-up and tender alerts that should exist now and do not yet, for the
 * whole database or one opportunity. Safe to run any number of times.
 */
export async function generateDeadlineAlerts(
  db: Database,
  options: { at?: Date; opportunityId?: string } = {},
): Promise<number> {
  const at = options.at ?? now();
  const today = dhakaDateOf(at);
  const onlyOpportunity = options.opportunityId ? eq(opportunities.id, options.opportunityId) : undefined;

  // Follow-ups due today, and overdue ones (FR-090; due date in Dhaka, FR-043).
  const taskType = sql<NotificationType>`(CASE WHEN ${followUps.dueDate} = ${today}::date
    THEN 'follow_up_due_today' ELSE 'follow_up_overdue' END)`;
  const taskKey = sql<string>`(${taskType} || ':' || ${recipient.id} || ':' || ${followUps.id} || ':' || ${followUps.dueDate}::text)`;
  const taskRows = await db
    .select({
      recipientId: recipient.id,
      opportunityId: opportunities.id,
      followUpId: followUps.id,
      type: taskType,
      triggerKey: taskKey,
      triggerDate: followUps.dueDate,
    })
    .from(followUps)
    .innerJoin(opportunities, eq(opportunities.id, followUps.opportunityId))
    .innerJoin(recipient, alertRecipientSql(recipient, followUps.assignedUserId))
    .where(
      and(
        eq(followUps.state, 'open'),
        sql`${followUps.dueDate} <= ${today}::date`,
        opportunityOpen(),
        onlyOpportunity,
        notYetAlerted(taskKey),
      ),
    );

  // Current, participating notices due within 72 hours (FR-090, BR-040).
  const tenderKey = sql<string>`('tender_deadline:' || ${recipient.id} || ':' || ${tenders.id} || ':'
    || to_char(${tenders.submissionDeadline} AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'))`;
  const tenderRows = await db
    .select({
      recipientId: recipient.id,
      opportunityId: opportunities.id,
      tenderId: tenders.id,
      triggerKey: tenderKey,
      triggerAt: tenders.submissionDeadline,
    })
    .from(tenders)
    .innerJoin(opportunities, eq(opportunities.id, tenders.opportunityId))
    .innerJoin(recipient, alertRecipientSql(recipient, opportunities.ownerId))
    .where(
      and(
        tenderDueWithin(at, TENDER_DUE_SOON_HOURS),
        sql`${tenders.submissionDeadline} > ${at.toISOString()}::timestamptz`,
        onlyOpportunity,
        notYetAlerted(tenderKey),
      ),
    );

  return insertAlerts(
    db,
    [
      ...taskRows.map((row) => ({
        ...row,
        tenderId: null,
        triggerAt: null,
        subjectUserId: null,
      })),
      ...tenderRows.map((row) => ({
        ...row,
        followUpId: null,
        type: 'tender_deadline' as const,
        triggerDate: null,
        subjectUserId: null,
      })),
    ],
    at,
  );
}

/**
 * FR-090 "ownership changes": after a transfer, the new owner, the new
 * section's lead and management are told — except whoever made the change.
 * `version` is the opportunity's version after the transfer, so each
 * transfer is its own trigger.
 */
export async function generateOwnershipAlerts(
  db: Database,
  options: { opportunityId: string; newOwnerId: string; version: number; actorId: string; at?: Date },
): Promise<number> {
  const at = options.at ?? now();
  const key = sql<string>`('ownership_changed:' || ${recipient.id} || ':' || ${opportunities.id} || ':' || ${String(options.version)})`;
  const rows = await db
    .select({ recipientId: recipient.id, opportunityId: opportunities.id, triggerKey: key })
    .from(opportunities)
    .innerJoin(recipient, alertRecipientSql(recipient, sql`${options.newOwnerId}::uuid`))
    .where(
      and(
        eq(opportunities.id, options.opportunityId),
        // Only while the transfer is still the current state.
        eq(opportunities.ownerId, options.newOwnerId),
        eq(opportunities.version, options.version),
        sql`${recipient.id} <> ${options.actorId}`,
        notYetAlerted(key),
      ),
    );
  return insertAlerts(
    db,
    rows.map((row) => ({
      ...row,
      followUpId: null,
      tenderId: null,
      type: 'ownership_changed' as const,
      triggerDate: null,
      triggerAt: null,
      subjectUserId: options.newOwnerId,
    })),
    at,
  );
}

/**
 * For services that change what an opportunity's alerts say (task closed or
 * rescheduled, transfer, tender change, stage or status change). Inside the
 * caller's transaction, after its opportunity lock: obsolete alerts are
 * retired at once, so unread counts drop with the commit, and a refresh job
 * is queued to add any replacement alerts. Generation is kept out of the
 * business transaction so a scan inserting alerts can never deadlock with it.
 * Call `signalJobsEnqueued()` after the commit.
 */
export async function alertsChangedInTransaction(
  tx: Database,
  options: {
    opportunityId: string;
    resolution: string;
    followUpId?: string;
    ownership?: { newOwnerId: string; version: number; actorId: string };
  },
): Promise<void> {
  await retireObsoleteAlerts(tx, {
    resolution: options.resolution,
    opportunityId: options.opportunityId,
    ...(options.followUpId ? { followUpId: options.followUpId } : {}),
  });
  await enqueueJob(tx, {
    kind: 'notifications.refresh',
    payload: { opportunityId: options.opportunityId, ...(options.ownership ? { ownership: options.ownership } : {}) },
  });
}

/** The scheduled scan: retire what is obsolete, then add what is due. */
export async function runNotificationScan(db: Database, at: Date = now()): Promise<{ retired: number; created: number }> {
  const retired = await retireObsoleteAlerts(db, { resolution: 'obsolete', at });
  const created = await generateDeadlineAlerts(db, { at });
  return { retired, created };
}

// ---------------------------------------------------------------------------
// Reads
// ---------------------------------------------------------------------------

/** DD Mon YYYY, as the rest of the interface writes dates (src/app/ui/dates.ts). */
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const timeFormatter = new Intl.DateTimeFormat('en-GB', { timeZone: BUSINESS_TIME_ZONE, hour: '2-digit', minute: '2-digit', hourCycle: 'h23' });

function formatDate(value: string): string {
  const [year, month, day] = value.split('-');
  return `${day} ${MONTHS[Number(month) - 1]} ${year}`;
}

function formatInstant(value: Date): string {
  return `${formatDate(dhakaDateOf(value))}, ${timeFormatter.format(value)} ${BUSINESS_TIME_LABEL}`;
}

/** The recipient's own alerts that are still true and still permitted. */
function visibleTo(actor: Actor, at: Date): SQL {
  return and(eq(notifications.recipientId, actor.id), opportunityScope(actor), stillValid(at)) as SQL;
}

function baseQuery(db: Database) {
  return db
    .select({
      id: notifications.id,
      type: notifications.type,
      createdAt: notifications.createdAt,
      readAt: notifications.readAt,
      triggerDate: notifications.triggerDate,
      triggerAt: notifications.triggerAt,
      opportunityId: opportunities.id,
      opportunityName: opportunities.name,
      followUpTitle: followUps.title,
      assigneeName: assignee.fullName,
      tenderReference: tenders.reference,
      subjectId: subject.id,
      subjectName: subject.fullName,
    })
    .from(notifications)
    .innerJoin(opportunities, eq(opportunities.id, notifications.opportunityId))
    .innerJoin(recipient, eq(recipient.id, notifications.recipientId))
    .leftJoin(followUps, eq(followUps.id, notifications.followUpId))
    .leftJoin(assignee, eq(assignee.id, followUps.assignedUserId))
    .leftJoin(tenders, eq(tenders.id, notifications.tenderId))
    .leftJoin(subject, eq(subject.id, notifications.subjectUserId));
}

type Row = Awaited<ReturnType<ReturnType<typeof baseQuery>['execute']>>[number];

function toDto(actor: Actor, row: Row): NotificationDto {
  const common = { id: row.id, type: row.type, createdAt: row.createdAt.toISOString(), readAt: row.readAt?.toISOString() ?? null };
  switch (row.type) {
    case 'follow_up_due_today':
      return {
        ...common,
        title: `Due today: ${row.followUpTitle ?? 'Follow-up'}`,
        detail: `${row.opportunityName} · ${row.assigneeName ?? ''}`,
        tone: 'amber',
        path: `/opportunities/${row.opportunityId}?tab=activities`,
      };
    case 'follow_up_overdue':
      return {
        ...common,
        title: `Overdue: ${row.followUpTitle ?? 'Follow-up'}`,
        detail: `${row.opportunityName} · due ${row.triggerDate ? formatDate(row.triggerDate) : ''} · ${row.assigneeName ?? ''}`,
        tone: 'red',
        path: `/opportunities/${row.opportunityId}?tab=activities`,
      };
    case 'tender_deadline':
      return {
        ...common,
        title: `Tender due within 72 hours: ${row.tenderReference ?? ''}`,
        detail: `${row.opportunityName} · ${row.triggerAt ? formatInstant(row.triggerAt) : ''}`,
        tone: 'amber',
        path: `/opportunities/${row.opportunityId}?tab=tender`,
      };
    case 'ownership_changed':
      return {
        ...common,
        title: row.subjectId === actor.id ? `Assigned to you: ${row.opportunityName}` : `Ownership changed: ${row.opportunityName}`,
        detail: `Now owned by ${row.subjectName ?? ''} · ${formatInstant(row.createdAt)}`,
        tone: 'teal',
        path: `/opportunities/${row.opportunityId}`,
      };
  }
}

export async function unreadCount(db: Database, actor: Actor, at: Date = now()): Promise<number> {
  const [row] = await db
    .select({ value: sql<number>`count(*)::int` })
    .from(notifications)
    .innerJoin(opportunities, eq(opportunities.id, notifications.opportunityId))
    .innerJoin(recipient, eq(recipient.id, notifications.recipientId))
    .leftJoin(followUps, eq(followUps.id, notifications.followUpId))
    .leftJoin(tenders, eq(tenders.id, notifications.tenderId))
    .where(and(visibleTo(actor, at), isNull(notifications.readAt)));
  return row?.value ?? 0;
}

export async function listNotifications(
  db: Database,
  actor: Actor,
  query: { page: number; pageSize: number; unread?: 'true' | 'false' | undefined },
): Promise<NotificationListDto> {
  const at = now();
  const where = and(visibleTo(actor, at), query.unread === 'true' ? isNull(notifications.readAt) : undefined);
  const [total] = await db
    .select({ value: sql<number>`count(*)::int` })
    .from(notifications)
    .innerJoin(opportunities, eq(opportunities.id, notifications.opportunityId))
    .innerJoin(recipient, eq(recipient.id, notifications.recipientId))
    .leftJoin(followUps, eq(followUps.id, notifications.followUpId))
    .leftJoin(tenders, eq(tenders.id, notifications.tenderId))
    .where(where);
  const rows = await baseQuery(db)
    .where(where)
    .orderBy(sql`${notifications.readAt} IS NOT NULL`, desc(notifications.createdAt), asc(notifications.id))
    .limit(query.pageSize)
    .offset((query.page - 1) * query.pageSize);
  return {
    items: rows.map((row) => toDto(actor, row)),
    total: total?.value ?? 0,
    page: query.page,
    pageSize: query.pageSize,
    unreadCount: await unreadCount(db, actor, at),
  };
}

/**
 * Marks one alert read. An alert that is not the reader's, is obsolete, or
 * concerns a record they can no longer see is the standard 404 — following
 * a notification never reveals more than the record's own page would.
 */
export async function markNotificationRead(db: Database, actor: Actor, notificationId: string): Promise<NotificationDto> {
  const at = now();
  const [row] = await baseQuery(db).where(and(eq(notifications.id, notificationId), visibleTo(actor, at))).limit(1);
  if (!row) throw notFound(`notification ${notificationId} absent, obsolete or not for actor ${actor.id}`);
  // read_at only. The follow-up, tender and opportunity are not touched (BR-070).
  await db
    .update(notifications)
    .set({ readAt: sql`coalesce(${notifications.readAt}, ${at.toISOString()}::timestamptz)` })
    .where(and(eq(notifications.id, notificationId), eq(notifications.recipientId, actor.id)));
  return toDto(actor, { ...row, readAt: row.readAt ?? at });
}

export async function markAllNotificationsRead(db: Database, actor: Actor): Promise<number> {
  const at = now();
  const visibleIds = db
    .select({ id: notifications.id })
    .from(notifications)
    .innerJoin(opportunities, eq(opportunities.id, notifications.opportunityId))
    .innerJoin(recipient, eq(recipient.id, notifications.recipientId))
    .leftJoin(followUps, eq(followUps.id, notifications.followUpId))
    .leftJoin(tenders, eq(tenders.id, notifications.tenderId))
    .where(and(visibleTo(actor, at), isNull(notifications.readAt)));
  const updated = await db
    .update(notifications)
    .set({ readAt: at })
    .where(and(eq(notifications.recipientId, actor.id), sql`${notifications.id} IN (${visibleIds})`))
    .returning({ id: notifications.id });
  return updated.length;
}
