/**
 * Milestone 6: reports and audited CSV exports (FR-082, FR-083, BR-060,
 * SEC-002, SEC-005, AT-12).
 *
 * Exports are generated by the background job, which the tests run
 * explicitly with the real handlers.
 */
import { and, eq } from 'drizzle-orm';
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it } from 'vitest';

import type { DashboardDto, ReportDto, ReportExportDto } from '../../shared/api.js';
import { sumMoney } from '../../shared/money.js';
import { REPORT_KEYS } from '../../shared/reporting.js';
import { FixedClock, resetClock, setClock } from '../clock.js';
import { auditEvents, reportExports } from '../db/schema.js';
import { createJobHandlers } from '../jobs/handlers.js';
import { runDueJobs } from '../jobs/queue.js';
import { neutralizeFormula } from '../services/csv.js';
import { generateExport } from '../services/exports.js';
import {
  ABSENT_UUID,
  CSRF_HEADER,
  IDEMPOTENCY_HEADER,
  TEST_ORIGIN,
  createTestApp,
  emails,
  ids,
  nextIdempotencyKey,
  resetFixtures,
  send,
  signIn,
  type SignedInClient,
  type TestContext,
} from './helpers/harness.js';

const DEMO_NOW = '2026-10-02T10:00:00+06:00';

describe('reports and CSV exports (M6)', () => {
  let ctx: TestContext;

  beforeAll(() => {
    ctx = createTestApp();
  });
  afterAll(async () => {
    await ctx.close();
  });
  beforeEach(async () => {
    await resetFixtures();
    setClock(new FixedClock(DEMO_NOW));
  });
  afterEach(() => {
    resetClock();
  });

  const as = (email: string) => signIn(ctx.app, email);

  async function report(client: SignedInClient, key: string, query = ''): Promise<ReportDto> {
    return (await client.agent.get(`/api/reports/${key}${query}`).expect(200)).body as ReportDto;
  }

  async function runJobs() {
    return runDueJobs(ctx.database.db, createJobHandlers(ctx.database.db, { exportTtlHours: 24, exportMaxRows: 50_000 }));
  }

  /** Requests an export, runs the job, and downloads it. */
  async function exportCsv(client: SignedInClient, kind: string, filters: Record<string, string> = {}) {
    const requested = (await send(client, '/api/exports', { kind, filters }, nextIdempotencyKey('export')).expect(202))
      .body as ReportExportDto;
    expect(requested.status).toBe('queued');
    await runJobs();
    const status = (await client.agent.get(`/api/exports/${requested.id}`).expect(200)).body as ReportExportDto;
    expect(status.status).toBe('ready');
    const download = await client.agent.get(`/api/exports/${requested.id}/download`).expect(200);
    return { id: requested.id, status, response: download, text: download.text, rows: parseCsv(download.text) };
  }

  /** A strict CSV reader for the files we produce (quoted fields, CRLF). */
  function parseCsv(text: string): string[][] {
    expect(text.charCodeAt(0)).toBe(0xfeff);
    const body = text.slice(1);
    const rows: string[][] = [];
    let row: string[] = [];
    let field = '';
    let quoted = false;
    for (let index = 0; index < body.length; index += 1) {
      const character = body[index]!;
      if (quoted) {
        if (character === '"' && body[index + 1] === '"') {
          field += '"';
          index += 1;
        } else if (character === '"') {
          quoted = false;
        } else {
          field += character;
        }
      } else if (character === '"') {
        quoted = true;
      } else if (character === ',') {
        row.push(field);
        field = '';
      } else if (character === '\r' && body[index + 1] === '\n') {
        row.push(field);
        rows.push(row);
        row = [];
        field = '';
        index += 1;
      } else {
        field += character;
      }
    }
    return rows;
  }

  describe('reports (FR-082, BR-060)', () => {
    it('names the date basis of every report', async () => {
      const client = await as(emails.management);
      const bases: Record<string, string> = {};
      for (const key of REPORT_KEYS) bases[key] = (await report(client, key)).dateBasis.label;
      expect(bases).toEqual({
        pipeline: 'Opportunity created date',
        section_owner: 'Opportunity created date',
        overdue_follow_ups: 'Follow-up due date',
        upcoming_tenders: 'Tender submission deadline',
        outcomes: 'Award date (Awarded) or lost date (Lost)',
        lost_reasons: 'Lost date',
      });
    });

    it('scopes every report before counting and summing (SEC-002)', async () => {
      const management = await as(emails.management);
      const leadGA = await as(emails.leadGA);
      const leadIS = await as(emails.leadIS);
      const rafiq = await as(emails.salesGA1);

      for (const key of REPORT_KEYS) {
        const all = await report(management, key);
        const ga = await report(leadGA, key);
        const is = await report(leadIS, key);
        const own = await report(rafiq, key);
        // Row-per-record reports: the sections partition the organization.
        if (key === 'overdue_follow_ups' || key === 'upcoming_tenders' || key === 'outcomes') {
          expect(ga.total + is.total).toBe(all.total);
          expect(own.total).toBeLessThanOrEqual(ga.total);
        }
        // No GA report mentions an IS-only record, and vice versa.
        const gaText = JSON.stringify(ga);
        expect(gaText).not.toContain('Infrastructure & Security');
        expect(gaText).not.toContain('Imran Hossain');
        expect(JSON.stringify(is)).not.toContain('Rafiq Hasan');
        expect(JSON.stringify(own)).not.toContain('Tasnia Karim');
      }

      const pipeline = await report(leadGA, 'pipeline');
      const dashboard = (await leadGA.agent.get('/api/dashboard').expect(200)).body as DashboardDto;
      const summary = Object.fromEntries(pipeline.summary.map((item) => [item.label, item.value]));
      expect(summary['Active opportunities']).toBe(String(dashboard.kpis.activeOpportunities));
      expect(summary['Estimated active pipeline']).toBe(dashboard.kpis.estimatedActivePipeline);
      expect(summary['On Hold (not in active pipeline)']).toBe('14500000.00');
      // Every board lane is listed, in board order, with estimates only (D-006).
      expect(pipeline.items.map((row) => row.cells.lane)).toEqual([
        'Identified',
        'Initial Engagement',
        'Requirements Discussion',
        'Awaiting Tender',
        'Tender Published',
        'Bid Preparation',
        'Bid Submitted',
        'Evaluation',
        'Awarded',
        'Lost',
        'On Hold',
        'Cancelled',
      ]);
      expect(pipeline.items.find((row) => row.cells.lane === 'Awarded')?.cells.estimatedValue).toBe('38500000.00');

      const overdue = await report(management, 'overdue_follow_ups');
      const overdueSummary = Object.fromEntries(overdue.summary.map((item) => [item.label, item.value]));
      const managementDashboard = (await management.agent.get('/api/dashboard').expect(200)).body as DashboardDto;
      expect(overdueSummary['Overdue follow-ups']).toBe(String(managementDashboard.kpis.overdueFollowUps));

      const tenders = await report(management, 'upcoming_tenders');
      expect(tenders.summary.find((item) => item.label === 'Due within 7 days')?.value).toBe(
        String(managementDashboard.kpis.tendersDueNext7Days),
      );
    });

    it('keeps estimated and actual awarded values apart (D-006)', async () => {
      const outcomes = await report(await as(emails.management), 'outcomes', '?sort=reference&dir=asc');
      const awarded = outcomes.items.find((row) => row.cells.reference === 'OPP-900005');
      expect(awarded?.cells).toMatchObject({ estimatedValue: '26000000.00', awardedValue: '23500000.00', outcomeDate: '2026-10-01' });
      const lost = outcomes.items.find((row) => row.cells.reference === 'OPP-900006');
      expect(lost?.cells).toMatchObject({ awardedValue: null, outcomeDate: '2026-08-26', lostReason: expect.stringMatching(/^Price/) });
      expect(outcomes.summary.find((item) => item.label === 'Actual awarded value')?.value).toBe('91800000.00');
      expect(outcomes.undated).toEqual({ count: 0, note: expect.stringContaining('Every matching record') });
    });

    it('filters on the named date basis, Dhaka dates inclusive', async () => {
      const management = await as(emails.management);
      // Pipeline: created date. OPP-900004 was created 2026-09-18, OPP-900018 2026-09-22.
      const september = await report(management, 'pipeline', '?from=2026-09-18&to=2026-09-22');
      expect(september.summary.find((item) => item.label === 'Opportunities')?.value).toBe('2');
      // Outcomes: award date for Awarded, lost date for Lost.
      const q3 = await report(management, 'outcomes', '?from=2026-07-01&to=2026-09-30');
      expect(q3.items.map((row) => row.cells.reference).sort()).toEqual(['OPP-900006', 'OPP-900015', 'OPP-900017']);
      // Tenders: submission deadline (Dhaka date).
      const tenders = await report(management, 'upcoming_tenders', '?from=2026-10-05&to=2026-10-05');
      expect(tenders.items.map((row) => row.cells.reference)).toEqual(['PPDC/IT/2026/118']);
      // Overdue: due date.
      const overdue = await report(management, 'overdue_follow_ups', '?from=2026-09-30&to=2026-09-30');
      expect(overdue.total).toBe(1);
      await management.agent.get('/api/reports/pipeline?from=2026-10-05&to=2026-10-01').expect(422);
    });

    it('pages and sorts on the server with an allowlist', async () => {
      const management = await as(emails.management);
      const first = await report(management, 'outcomes', '?pageSize=2&page=1&sort=estimatedValue&dir=desc');
      const second = await report(management, 'outcomes', '?pageSize=2&page=2&sort=estimatedValue&dir=desc');
      expect(first.total).toBe(5);
      expect(first.items).toHaveLength(2);
      expect(first.items[0]?.cells.reference).toBe('OPP-900015');
      expect(second.items).toHaveLength(2);
      const values = [...first.items, ...second.items].map((row) => Number(row.cells.estimatedValue));
      expect(values).toEqual([...values].sort((a, b) => b - a));
      const byOpportunities = await report(management, 'pipeline', '?sort=opportunities&dir=desc');
      const counts = byOpportunities.items.map((row) => Number(row.cells.opportunities));
      expect(counts).toEqual([...counts].sort((a, b) => b - a));

      await management.agent.get('/api/reports/outcomes?sort=password').expect(422);
      await management.agent.get('/api/reports/lost_reasons?sort=opportunities').expect(422);
      await management.agent.get('/api/reports/outcomes?pageSize=101').expect(422);
      await management.agent.get('/api/reports/outcomes?page=0').expect(422);
      await management.agent.get('/api/reports/outcomes?unknown=1').expect(422);
      await management.agent.get('/api/reports/nonexistent').expect(404);
    });

    it('applies the FR-082 filter rules and refuses the administrator', async () => {
      const rafiq = await as(emails.salesGA1);
      await rafiq.agent.get(`/api/reports/pipeline?ownerId=${ids.salesGA2}`).expect(403);
      const lead = await as(emails.leadGA);
      await lead.agent.get(`/api/reports/pipeline?sectionId=${ids.sectionIS}`).expect(403);
      const narrowed = await report(lead, 'section_owner', `?ownerId=${ids.salesIS1}`);
      expect(narrowed.total).toBe(0);
      const management = await as(emails.management);
      const is = await report(management, 'section_owner', `?sectionId=${ids.sectionIS}`);
      expect(is.items.every((row) => row.cells.section === 'Infrastructure & Security')).toBe(true);

      const admin = await as(emails.admin);
      for (const key of REPORT_KEYS) await admin.agent.get(`/api/reports/${key}`).expect(403);
    });

    it('lists lost reasons with their estimated value', async () => {
      const lost = await report(await as(emails.management), 'lost_reasons');
      expect(lost.items.map((row) => row.cells)).toEqual([
        { reason: expect.any(String), count: 1, estimatedValue: expect.any(String), opportunities: expect.any(String) },
        { reason: expect.any(String), count: 1, estimatedValue: expect.any(String), opportunities: expect.any(String) },
      ]);
      expect(sumMoney(lost.items.map((row) => String(row.cells.estimatedValue)))).toBe('47000000.00');
    });
  });

  describe('CSV export (FR-083, AT-12)', () => {
    it('exports every matching record, not just one page, with the list population', async () => {
      const lead = await as(emails.leadGA);
      const board = (await lead.agent.get('/api/dashboard').expect(200)).body as DashboardDto;
      const { rows, response, status } = await exportCsv(lead, 'opportunities', { pipeline: 'active', pageSize: '2', page: '1' });

      expect(response.headers['content-type']).toBe('text/csv; charset=utf-8');
      expect(response.headers['content-disposition']).toMatch(/^attachment; filename="penta-opportunities-2026-10-02\.csv"$/);
      expect(response.headers['cache-control']).toBe('private, no-store');
      const [header, ...data] = rows;
      expect(header).toContain('Estimated value (BDT)');
      expect(header).toContain('Created (Bangladesh time, UTC+6)');
      // AT-12: dashboard count and value = list = export.
      expect(data).toHaveLength(board.kpis.activeOpportunities);
      expect(status.rowCount).toBe(board.kpis.activeOpportunities);
      const valueColumn = header!.indexOf('Estimated value (BDT)');
      expect(sumMoney(data.map((row) => row[valueColumn]!))).toBe(board.kpis.estimatedActivePipeline);
      // Unformatted decimals, ISO instants with the Dhaka offset, Bangla intact.
      expect(data.every((row) => /^\d+\.\d{2}$/.test(row[valueColumn]!))).toBe(true);
      const created = header!.indexOf('Created (Bangladesh time, UTC+6)');
      expect(data.every((row) => /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\+06:00$/.test(row[created]!))).toBe(true);
      expect(data.some((row) => row.includes('উপজেলা পর্যায়ের চাহিদা যাচাই করুন'))).toBe(true);
    });

    it('exports a report with the same rows and columns as the screen', async () => {
      const management = await as(emails.management);
      const screen = await report(management, 'outcomes', '?pageSize=2');
      const { rows } = await exportCsv(management, 'outcomes');
      expect(rows[0]).toEqual(screen.columns.map((column) => column.label));
      expect(rows).toHaveLength(screen.total + 1);
    });

    it('excludes inaccessible data from every export (AT-02, AT-03)', async () => {
      const rafiq = await as(emails.salesGA1);
      const { text } = await exportCsv(rafiq, 'opportunities');
      expect(text).not.toContain('Tasnia Karim');
      expect(text).not.toContain('Infrastructure & Security');
      const leadIS = await as(emails.leadIS);
      const isExport = await exportCsv(leadIS, 'overdue_follow_ups');
      expect(isExport.text).not.toContain('Government Applications');
    });

    it('neutralizes formula injection in user-entered cells', async () => {
      expect(neutralizeFormula('=HYPERLINK("http://x","y")')).toBe(`'=HYPERLINK("http://x","y")`);
      for (const hostile of ['+1+1', '-2+3', '@SUM(A1)', '\t=1', '\r=1', '  =1', '＝1', '＠x']) {
        expect(neutralizeFormula(hostile).startsWith("'")).toBe(true);
      }
      expect(neutralizeFormula('Ordinary name')).toBe('Ordinary name');
      expect(neutralizeFormula('বাংলা')).toBe('বাংলা');

      const rafiq = await as(emails.salesGA1);
      const detail = (await rafiq.agent.get(`/api/opportunities/${ids.oppRafiq}`).expect(200)).body;
      await rafiq.agent
        .patch(`/api/opportunities/${ids.oppRafiq}`)
        .set('Origin', TEST_ORIGIN)
        .set(CSRF_HEADER, rafiq.csrfToken)
        .send({ version: detail.version, name: '=cmd|"/C calc"!A0' })
        .expect(200);
      const { rows } = await exportCsv(rafiq, 'opportunities');
      const header = rows[0]!;
      const names = rows.slice(1).map((row) => row[header.indexOf('Opportunity')]);
      expect(names).toContain(`'=cmd|"/C calc"!A0`);
      expect(names.some((name) => name?.startsWith('='))).toBe(false);
    });

    it('audits who exported which report and how many records', async () => {
      const lead = await as(emails.leadGA);
      const { id, status } = await exportCsv(lead, 'pipeline', { from: '2026-01-01' });
      const events = await ctx.database.db
        .select()
        .from(auditEvents)
        .where(eq(auditEvents.entityId, id))
        .orderBy(auditEvents.occurredAt);
      expect(events.map((event) => event.action)).toEqual([
        'report.export_requested',
        'report.exported',
        'report.export_downloaded',
      ]);
      expect(events.every((event) => event.actorId === ids.leadGA && event.domain === 'reporting')).toBe(true);
      expect(events[1]?.afterData).toMatchObject({ kind: 'pipeline', rowCount: status.rowCount, filters: { from: '2026-01-01' } });
      // Never part of an opportunity's commercial history.
      expect(events.every((event) => event.opportunityId === null)).toBe(true);
    });

    it('rechecks access before delivering a queued export (SEC-005)', async () => {
      const rafiq = await as(emails.salesGA1);
      const requested = (await send(rafiq, '/api/exports', { kind: 'opportunities', filters: {} }, nextIdempotencyKey('export')).expect(202))
        .body as ReportExportDto;
      await runJobs();

      // One of the exported records is transferred away before download.
      const lead = await as(emails.leadGA);
      const detail = (await lead.agent.get(`/api/opportunities/${ids.oppRafiq}`).expect(200)).body;
      await send(
        lead,
        `/api/opportunities/${ids.oppRafiq}/transfer`,
        { version: detail.version, newOwnerId: ids.salesGA2, reason: 'Reassigned' },
        nextIdempotencyKey('m6'),
      ).expect(200);

      const refused = await rafiq.agent.get(`/api/exports/${requested.id}/download`).expect(409);
      expect(refused.body.code).toBe('export_unavailable');
      expect(refused.text).not.toContain('Municipal');
    });

    it('fails an export whose requester lost access before it was produced', async () => {
      const lead = await as(emails.leadGA);
      const requested = (await send(lead, '/api/exports', { kind: 'pipeline', filters: {} }, nextIdempotencyKey('export')).expect(202))
        .body as ReportExportDto;
      // Deactivate the requester directly before the job runs.
      const { users } = await import('../db/schema.js');
      await ctx.database.db.update(users).set({ active: false }).where(eq(users.id, ids.leadGA));
      await runJobs();
      const [row] = await ctx.database.db.select().from(reportExports).where(eq(reportExports.id, requested.id));
      expect(row?.status).toBe('failed');
      expect(row?.content).toBeNull();
    });

    it('shows an export only to the person who requested it', async () => {
      const management = await as(emails.management);
      const { id } = await exportCsv(management, 'pipeline');
      const lead = await as(emails.leadGA);
      const missing = await lead.agent.get(`/api/exports/${ABSENT_UUID}`).expect(404);
      const other = await lead.agent.get(`/api/exports/${id}`).expect(404);
      const { requestId: _a, ...missingBody } = missing.body;
      const { requestId: _b, ...otherBody } = other.body;
      expect(otherBody).toEqual(missingBody);
      await lead.agent.get(`/api/exports/${id}/download`).expect(404);
      const admin = await as(emails.admin);
      await admin.agent.get(`/api/exports/${id}`).expect(404);
      await send(admin, '/api/exports', { kind: 'pipeline', filters: {} }, nextIdempotencyKey('export')).expect(403);
    });

    it('validates export filters with the screen’s own rules', async () => {
      const rafiq = await as(emails.salesGA1);
      await send(rafiq, '/api/exports', { kind: 'pipeline', filters: { ownerId: ids.salesGA2 } }, nextIdempotencyKey('e')).expect(403);
      await send(rafiq, '/api/exports', { kind: 'pipeline', filters: { sort: 'secret' } }, nextIdempotencyKey('e')).expect(422);
      await send(rafiq, '/api/exports', { kind: 'opportunities', filters: { stage: 'won' } }, nextIdempotencyKey('e')).expect(422);
      await send(rafiq, '/api/exports', { kind: 'everything', filters: {} }, nextIdempotencyKey('e')).expect(422);
      await send(rafiq, '/api/exports', { kind: 'pipeline', filters: {} }, null).expect(422);
      // CSRF is required.
      await rafiq.agent
        .post('/api/exports')
        .set('Origin', TEST_ORIGIN)
        .set(IDEMPOTENCY_HEADER, nextIdempotencyKey('e'))
        .send({ kind: 'pipeline', filters: {} })
        .expect(403);
      const exportCount = await ctx.database.db.select().from(reportExports);
      expect(exportCount).toHaveLength(0);
    });

    it('creates one export for a retried request', async () => {
      const lead = await as(emails.leadGA);
      const key = nextIdempotencyKey('export');
      const first = await send(lead, '/api/exports', { kind: 'pipeline', filters: {} }, key).expect(202);
      const retry = await send(lead, '/api/exports', { kind: 'pipeline', filters: {} }, key).expect(200);
      expect(retry.body.id).toBe(first.body.id);
      await send(lead, '/api/exports', { kind: 'outcomes', filters: {} }, key).expect(409);
      const rows = await ctx.database.db.select().from(reportExports);
      expect(rows).toHaveLength(1);
      const requested = await ctx.database.db
        .select()
        .from(auditEvents)
        .where(and(eq(auditEvents.action, 'report.export_requested'), eq(auditEvents.entityId, first.body.id)));
      expect(requested).toHaveLength(1);
    });

    it('refuses rather than truncates an export over the row limit', async () => {
      const management = await as(emails.management);
      const requested = (await send(management, '/api/exports', { kind: 'opportunities', filters: {} }, nextIdempotencyKey('e')).expect(202))
        .body as ReportExportDto;
      await generateExport(ctx.database.db, requested.id, { ttlHours: 24, maxRows: 5 });
      const status = (await management.agent.get(`/api/exports/${requested.id}`).expect(200)).body as ReportExportDto;
      expect(status.status).toBe('failed');
      expect(status.failureReason).toMatch(/More than 5 rows/);
      await management.agent.get(`/api/exports/${requested.id}/download`).expect(409);
    });

    it('expires a ready export', async () => {
      const lead = await as(emails.leadGA);
      const { id } = await exportCsv(lead, 'pipeline');
      setClock(new FixedClock('2026-10-03T10:00:01+06:00'));
      const later = await as(emails.leadGA);
      const response = await later.agent.get(`/api/exports/${id}/download`).expect(409);
      expect(response.body.message).toMatch(/expired/);
    });
  });
});
